version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install --save react-bootstrap bootstrap
      - npm install
  build:
    commands:
      - npm run build


artifacts:
  base-directory: 'build'
  files:
    - '**/*'
